### PR TITLE
insertion and deletion in Singly  and Doubly Linked list 

### PR DESCRIPTION
**Pull request by Arisha2902**
insertion and deletion in Singly  and Doubly Linked list at starting, ending  and kth position

### CODE REVIEW

**Comment by Arisha2902** [comment]
This was my first time contributing to open source using Git. Previously, I have primarily worked through GitHub’s web interface. I suspect the issue occurred during my first commit while I was learning Git. If there are any errors in my approach or workflow, please let me know so I can address them and improve.

**Comment by Yaser-123** [comment]
It’s showing 41 files because your branch has extra changes from earlier commits. To fix it, create a new branch from the main branch, add only the new file, and push that branch. Then make a PR again. This will ensure only the new file is included.

Screenshot_20241122_183053_Chrome

**Comment by Arisha2902** [comment]
The issue is from your side, your repo can't be cloned properly so it is creating further changes.
Even if I try to create a new branch , it doesn't work.

**Comment by Yaser-123** [comment]
@Arisha2902 

Another friend created a PR #7  to verify, and it worked perfectly. Looks like the issue is on your end. Check the screenshot for reference. Make sure your fork is fully synced and you're working from a clean branch before trying again.

Screenshot 2024-11-22 200304

**Comment by Arisha2902** [comment]
my code have already been merged to your repo, there were some issue ,that this @mohamedammar27 this resolved.
And my changes were accepted ,right now ur repo already has code.  The issue has been resolved and merged in your repo already

**Comment by Yaser-123** [comment]
I believe there’s been a misunderstanding. You still have 41 files changed, and as for the file you mentioned, it was added by my friend, @mohamedammar27.

To correct your PR, follow these steps:

1. Sync your fork with the main branch.
2. Create a new branch from the synced fork.
3. Add only your changes and submit a new PR.

Let me know if you need further clarification!

**Comment by Arisha2902** [comment]
My files have been already added in your code ,If I will do it again then it will just add extra files only, or overwrite the files

**Pull request closed without merging**
